Assignment 4

In [1]:
import numpy as np

Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:\
a) Addition of 2 in all the element\
b) Multiply 3 with all the elements\
c) Divide every element by 2

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6])

arr_plus_2 = arr + 2

arr_times_3 = arr * 3

arr_by_2 = arr / 2

print("Original Array:", arr)
print("After Adding 2:", arr_plus_2)
print("After Multiplying by 3:", arr_times_3)
print("After Dividing by 2:", arr_by_2)

Original Array: [1 2 3 4 5 6]
After Adding 2: [3 4 5 6 7 8]
After Multiplying by 3: [ 3  6  9 12 15 18]
After Dividing by 2: [0.5 1.  1.5 2.  2.5 3. ]


Q2: Basic NumPy Array Operations\
(a) Reverse a NumPy array

In [4]:
arr = np.array([1, 5, 6, 3, 4, 2])

arr_rev = arr[::-1]

print("Original Array: ", arr, " , reversed array: ", arr_rev)

Original Array:  [1 5 6 3 4 2]  , reversed array:  [2 4 3 6 5 1]


(b) Find the most frequent value and its indices\
i. x = np.array([1,2,3,4,5,1,2,1,1,1])\
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
max_x = np.bincount(x).argmax()
max_x_indices = np.where(x == max_x)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
max_y = np.bincount(y).argmax()
max_y_indices = np.where(y == max_y)

print(f"Most Frequent Value in x: {max_x}, and the Indices: {max_x_indices}")
print(f"Most Frequent Value in x: {max_y}, and the Indices: {max_y_indices}")

Most Frequent Value in x: 1, and the Indices: (array([0, 5, 7, 8, 9]),)
Most Frequent Value in x: 1, and the Indices: (array([0, 1, 2]),)


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:\
a) Access 1st row, 2nd column\
b) Access 3rd row, 1st column

In [8]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Element at 1st row, 2nd column:", arr[0, 1])
print("Element at 3rd row, 1st column:", arr[2, 0])

Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [10]:
mukul = np.linspace(10, 100, 25)

print("Array Dimensions:", mukul.ndim)
print("Array Shape:", mukul.shape)
print("Total Elements:", mukul.size)
print("Data Type:", mukul.dtype)
print("Total Bytes Consumed:", mukul.nbytes)

transposed_array = mukul.reshape(-1, 1)

print("Can we use .T for 1D array?", mukul.T.shape)

print("Reshaped Transpose Array:\n", transposed_array)

Array Dimensions: 1
Array Shape: (25,)
Total Elements: 25
Data Type: float64
Total Bytes Consumed: 200
Can we use .T for 1D array? (25,)
Reshaped Transpose Array:
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [11]:
ucs420_mukul = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Mean:", np.mean(ucs420_mukul))
print("Median:", np.median(ucs420_mukul))
print("Max:", np.max(ucs420_mukul))
print("Min:", np.min(ucs420_mukul))
print("Unique Elements:", np.unique(ucs420_mukul))

reshaped_ucs420_mukul = ucs420_mukul.reshape(4, 3)
print("Reshaped Array (4x3):\n", reshaped_ucs420_mukul)

resized_ucs420_mukul = ucs420_mukul.reshape(2, -1)
print("Resized Array (2x6):\n", resized_ucs420_mukul)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array (2x6):
 [[10 20 30 40 50 60]
 [70 80 90 15 20 35]]
